###########
# site.title

title:    'The Building Company'
subtitle: 'Expert builders in Milton Keynes & surrounding areas.'
description: 'Expert builders in Milton Keynes & surrounding areas.'


#########################
# more settings

markdown: kramdown

sass:
  style: compressed

exclude:
- README.md
- LICENSE.md
